services:
  redisHandler-redis:
    image: 'docker.io/bitnami/redis:6.2-debian-10'
    container_name: redisHandler-redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/bitnami/redis/data
      - redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  redis_data:
  redis.conf:
